import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { ClassroomJoin } from '@/components/classroom/classroom-join'

export const metadata: Metadata = { title: 'Join a classroom' }

export default async function ClassroomJoinPage({
  params,
}: {
  params: Promise<{ code: string }>
}) {
  const { code } = await params

  // Invite codes are twelve hex characters, generated by `gen_random_bytes(6)`.
  // Anything else is a mistyped URL rather than a classroom, and it should say
  // so instead of asking the database about it.
  if (!/^[0-9a-f]{12}$/.test(code)) notFound()

  return <ClassroomJoin code={code} />
}
