#!/usr/bin/env node
/**
 * Generates per-app env files from the single root `.env`.
 *
 * The root `.env` is the only place a secret is written by hand. This script
 * derives what each deployable actually needs, and deliberately refuses to put
 * a service-role key or the OpenRouter key anywhere the browser can reach.
 *
 * On a hosting platform there is no root `.env` to read — the environment
 * itself is where the secrets arrive. When the file is absent the process
 * environment stands in for it, so a Vercel build sets exactly the same
 * variable names a developer puts in `.env` and nothing else has to change.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

function parseEnv(text) {
  const out = {}
  for (const line of text.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq === -1) continue
    const key = trimmed.slice(0, eq).trim()
    let value = trimmed.slice(eq + 1).trim()
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }
    out[key] = value
  }
  return out
}

const envPath = resolve(root, '.env')
const fromFile = existsSync(envPath)
const env = fromFile ? parseEnv(readFileSync(envPath, 'utf8')) : process.env
const source = fromFile ? '.env' : 'the environment'

const required = ['SUPABASE_URL', 'SUPABASE_PUBLISHABLE_KEY', 'SUPABASE_SERVICE_ROLE_KEY']
const missing = required.filter((k) => !env[k])
if (missing.length) {
  console.error(`Missing required keys in ${source}: ${missing.join(', ')}`)
  if (!fromFile) {
    console.error('No .env at the repo root either. Copy .env.example and fill it in.')
  }
  process.exit(1)
}

const optional = (key, fallback = '') => env[key] ?? fallback

// --- apps/web -------------------------------------------------------------
// NEXT_PUBLIC_* is shipped to the browser. Everything else stays server-side.
const web = [
  '# Generated by scripts/sync-env.mjs — do not edit, edit the root .env',
  '',
  '# Public (shipped to the browser)',
  `NEXT_PUBLIC_SUPABASE_URL=${env.SUPABASE_URL}`,
  `NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${env.SUPABASE_PUBLISHABLE_KEY}`,
  `NEXT_PUBLIC_SITE_URL=${optional('SITE_URL', 'http://localhost:3000')}`,
  `NEXT_PUBLIC_VAPID_PUBLIC_KEY=${optional('VAPID_PUBLIC_KEY')}`,
  `NEXT_PUBLIC_REPO_URL=${optional('NEXT_PUBLIC_REPO_URL')}`,
  `NEXT_PUBLIC_CAMPUS_TOUR_URL=${optional('NEXT_PUBLIC_CAMPUS_TOUR_URL')}`,
  '',
  '# Server-only. Never referenced from a client component.',
  `SUPABASE_SERVICE_ROLE_KEY=${env.SUPABASE_SERVICE_ROLE_KEY}`,
  `SUPABASE_CONNECTION_STRING=${optional('SUPABASE_CONNECTION_STRING')}`,
  `OPENROUTER_API_KEY=${optional('OPENROUTER_API_KEY')}`,
  `WORKER_URL=${optional('WORKER_URL', 'http://localhost:8787')}`,
  `WORKER_SECRET=${optional('WORKER_SECRET', 'dev-worker-secret')}`,
  `VAPID_PRIVATE_KEY=${optional('VAPID_PRIVATE_KEY')}`,
  `VAPID_SUBJECT=${optional('VAPID_SUBJECT', 'mailto:hello@onetup.ph')}`,
  '',
  '# AI model ladder (ADR-006: model choice is configuration, not code)',
  `AI_TIER_FAST=${optional('AI_TIER_FAST')}`,
  `AI_TIER_STANDARD=${optional('AI_TIER_STANDARD')}`,
  `AI_TIER_LONG=${optional('AI_TIER_LONG')}`,
  `AI_TIER_REASON=${optional('AI_TIER_REASON')}`,
  `AI_TIER_VISION=${optional('AI_TIER_VISION')}`,
  '',
].join('\n')

writeFileSync(resolve(root, 'apps/web/.env.local'), web)

// --- apps/worker ----------------------------------------------------------
// ADR-004 / auth doc §4.2: the worker gets NO database credentials, ever.
const worker = [
  '# Generated by scripts/sync-env.mjs — do not edit, edit the root .env',
  '#',
  '# The sync worker deliberately holds no Supabase credentials of any kind.',
  '# See 07-AUTH-ERS.md §4.2: compromising it must yield nothing at rest.',
  '',
  `PORT=${optional('WORKER_PORT', '8787')}`,
  `WORKER_SECRET=${optional('WORKER_SECRET', 'dev-worker-secret')}`,
  `ERS_BASE_URL=${optional('ERS_BASE_URL', 'https://ers.tup.edu.ph/aims/students/')}`,
  `WORKER_MAX_CONCURRENCY=${optional('WORKER_MAX_CONCURRENCY', '10')}`,
  `WORKER_JOB_TIMEOUT_MS=${optional('WORKER_JOB_TIMEOUT_MS', '60000')}`,
  '',
].join('\n')

writeFileSync(resolve(root, 'apps/worker/.env'), worker)

console.log(`env: wrote apps/web/.env.local and apps/worker/.env from ${source}`)
